feat: add profile launch gst capi face_detection
jim-wang-intel/vision-self-checkout pull request #1
Opened 2023-10-05 19:54 UTC by vli11

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?
add feature: gst capi face_detection profile

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable
1. make build-gst-capi
2. ./camera-simulator/camera-simulator.sh
3. PIPELINE_PROFILE="face_detection" RENDER_MODE=1 sudo -E ./run.sh --workload ovms --inputsrc rtsp://127.0.0.1:8554/camera_0 --platform core

after above 3 commands, you should see video streaming result of inferencing popped up.

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2023-10-05 20:18 UTC, brian-intel commented on configs/opencv-ovms/gst_capi/Makefile
> +	wget -O ovms.tar.gz https://github.com/openvinotoolkit/model_server/releases/download/v2023.0/ovms_ubuntu22.tar.gz
I believe this is unused now that we are pulling the latest OVMS image from Dockerhub

2023-10-05 20:27 UTC, brian-intel commented on configs/opencv-ovms/gst_capi/get-media-codec.sh
> +    is_avc=`gst-discoverer-1.0 $1 | grep -i h.264 | wc -l`
Is it possible to move this logic into the launch-pipeline.sh. It seems a bit overkill to have a separate script for a single function.

2023-10-05 20:31 UTC, vli11 commented on configs/opencv-ovms/gst_capi/Makefile
> +	wget -O ovms.tar.gz https://github.com/openvinotoolkit/model_server/releases/download/v2023.0/ovms_ubuntu22.tar.gz
we need the ovms/lib in the container to build the face_detection c++ code @brian-intel

2023-10-05 22:14 UTC, ejlee3 commented on configs/opencv-ovms/gst_capi/Dockerfile.ovms-capi-gst
> +COPY gst_capi/get-media-codec.sh /home/intel/gst-ovms/get-media-codec.sh
this line is breaking the build

2023-10-05 22:58 UTC, ejlee3 approved these changes
LGTM - tested on my linux nuc. One thing: is there a good way to bring things down and clean up the services?

2023-10-06 16:03 UTC, brian-intel approved these changes

2023-10-06 16:22 UTC, jim-wang-intel requested changes

2023-10-06 16:22 UTC, jim-wang-intel commented on Makefile
please also add the `clean-gst-capi` make target and add that target as dependency of clean-profile-launcher as well

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +        //     network_h, network_w, numberOfDetections, objectSize, outData[0 * objectSize + 0], outData[0 * objectSize + 1]);
remvoe

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +            //printf("Confidence found: %f\n", confidence);
remove

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +                //printf("Confidence found: %f\n", confidence);
remove

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +        //printf("--------->coords: %f %f %f %f\n", x0, y0, x1, y1);
remove

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +        //std::cout << "xDrawing at " << (int)obj.x*scaler_w << "," << (int)obj.y*scaler_h << " " << (int)(obj.x+obj.width)*scaler_w << " " << (int) (obj.y+obj.height)* scaler_h << std::endl;
remvoe

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +                //cv::imwrite("faceresized.jpg", analytics_frame);
remove

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +        //  << ", OutputCount " << outputCount << std::endl;
remove

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +            //saveInferenceResultsAsVideo(img, detectedResultsFiltered);
remove

2023-10-06 16:22 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
> +    //string cmd = "cids=$(docker ps  --filter=\"name=gst-ovms\" -q -a); cid_count=`echo \"$cids\" | wc -w`; echo $cid_count";
remove

2023-10-06 16:22 UTC, jim-wang-intel commented on download_models/downloadGSTCAPIModels.sh
why do we need this script?  isn't the current model-downloader from omz-downloader not working?

2023-10-06 16:22 UTC, jim-wang-intel commented on download_models/getModels.sh
> +    "$MODEL_EXEC_PATH"/downloadGSTCAPIModels.sh $REFRESH_INPUT
remove if this special script is not needed

2023-10-06 16:27 UTC, jim-wang-intel commented on configs/opencv-ovms/scripts/run_face_detection.sh
> +bash_cmd="cd pipelines && chmod +x build-demos.sh && ./build-demos.sh && cd .. && ./launch-pipeline.sh $PIPELINE_EXEC_PATH $INPUTSRC $USE_ONEVPL $RENDER_MODE $RENDER_PORTRAIT_MODE"
if we could, maybe worth investigating change this $INPUTSRC to $inputsrc so that we don't change run_ovms.sh at all

2023-10-06 16:51 UTC, vli11 commented on download_models/downloadGSTCAPIModels.sh
this is just to keep gst capi model separately, it is cleaner; and in case we want to separate the model download process, its already so.

2023-10-06 16:52 UTC, vli11 commented on configs/opencv-ovms/scripts/run_face_detection.sh
> +bash_cmd="cd pipelines && chmod +x build-demos.sh && ./build-demos.sh && cd .. && ./launch-pipeline.sh $PIPELINE_EXEC_PATH $INPUTSRC $USE_ONEVPL $RENDER_MODE $RENDER_PORTRAIT_MODE"
I can log an issue since $INPUTSRC to $inputsrc can impact other profile run.

2023-10-06 18:29 UTC, vli11 commented on configs/opencv-ovms/scripts/run_face_detection.sh
> +bash_cmd="cd pipelines && chmod +x build-demos.sh && ./build-demos.sh && cd .. && ./launch-pipeline.sh $PIPELINE_EXEC_PATH $INPUTSRC $USE_ONEVPL $RENDER_MODE $RENDER_PORTRAIT_MODE"
https://github.com/intel-retail/automated-self-checkout/issues/291 created

2023-10-16 17:09 UTC, vli11 commented
PR moved to main, closing this one

2023-10-16 17:09 UTC, closed without merging